# Generated by Django 4.2.7 on 2023-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0019_auto_20191125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvariable',
            name='success_sign_up',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer1',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer2',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='level',
            name='answer3',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_answer',
            field=models.CharField(max_length=10000),
        ),
    ]
